version: '3'

services:
  src:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest_api_conteiner
    tty: true
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/src
    environment:
      MONGODB_DATABASE: 'API_course_money'
      MONGODB_USERNAME: 'alex'
      MONGODB_PASSWORD: 'nazca007'
      MONGODB_HOSTNAME: mongodb
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: "mongodb"
    ports:
      - "27020:27020"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'alex'
      MONGO_INITDB_ROOT_PASSWORD: 'nazca007'
      MONGO_INITDB_DATABASE: 'API_course_money'
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

volumes:
  mongo-data:
  mongo-configdb: